name: Upload Thunderstore Package

on:
  push:
    tags:
      - "*"

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Upload Thunderstore Package
        uses: GreenTF/upload-thunderstore-package@v4.3
        with:
          namespace: TheField
          community: peak
          token: ${{ secrets.TCLI_AUTH_TOKEN }}
          name: TheFieldMixtape
          description: The Field's Mixtape
          version: 1.0.0
          deps: onlystar-sPEAKer@2.3.6
